package Menu;

public enum ScreenType {
	
	NONE, MODE_SCREEN, FORREST_TRACK_SELECTOR, CAR_SELECTOR, CAR_BUILDER, CAR_MODE_SCREEN, ARCTIC_TRACK_SELECTOR, INFINITE_TRACK_SELECTOR, MAIN_MENU_SCREEN, PAUSE_DIALOG, CHALLENGE_LOBBY, CHALLENGE_CREATION

}
